import meta from "./meta.html";

// THE WORKER SCRIPT TO EXECUTE
// This is where you'd dynamically inject different scripts
const workerScript = `
    const workerScript = async (request, env, ctx) => {
      const url = new URL(request.url);
      const path = url.pathname;

      // Example routing logic
      if (path === "/api/hello") {
        return new Response(
          JSON.stringify({
            message: "Hello from JS Worker!",
            timestamp: new Date().toISOString(),
            path: path,
            userAgent: request.headers.get("User-Agent"),
          }),
          {
            headers: { "Content-Type": "application/json" },
          },
        );
      }

      if (path === "/api/env") {
        return new Response(
          JSON.stringify({
            env: env,
            availableKeys: Object.keys(env),
          }),
          {
            headers: { "Content-Type": "application/json" },
          },
        );
      }

      if (path.startsWith("/api/echo/")) {
        const message = path.split("/api/echo/")[1];
        return new Response(
          \`
                    <html><head><title>My website</title></head><body>
                    <h1>Echo Response</h1>
                    <p>You said: <strong>\${decodeURIComponent(message)}</strong></p>
                    <p>Current time: \${new Date().toLocaleString()}</p>
                    <p>Request URL: \${request.url}</p>
                    <hr>
                    <a href="/api/hello">Try /api/hello</a> | 
                    <a href="/api/env">Try /api/env</a> |
                    <a href="/api/echo/test%20message">Try /api/echo/test message</a>
                    </body></html>
                \`,
          {
            headers: { "Content-Type": "text/html" },
          },
        );
      }

      // Default response
      return new Response(
        \`
                <html><head><title>My website</title></head><body>
                <h1>JS Worker Runtime</h1>
                <p>Current path: <code>\${path}</code></p>
                <p>Available endpoints:</p>
                <ul>
                    <li><a href="/api/hello">/api/hello</a> - JSON response</li>
                    <li><a href="/api/env">/api/env</a> - Environment variables</li>
                    <li><a href="/api/echo/your-message">/api/echo/your-message</a> - Echo service</li>
                </ul>
                <hr>
                <p><small>This page was generated by a JavaScript function running in your browser, 
                simulating a Cloudflare Worker!</small></p>
                </body></html>
            \`,
        {
          headers: { "Content-Type": "text/html" },
        },
      );
    };`;

export default {
  async fetch(request, env, ctx) {
    return new Response(meta.replace("<script>", "<script>\n" + workerScript), {
      headers: {
        "Content-Type": "text/html;charset=UTF-8",
      },
    });
  },
};
